alias g       'grep -i'
alias lll     'll -a'
alias coff    'coffee -mwc .'
alias canary  'open -a Google\ Chrome\ Canary --args --disable-web-security'
alias snoop   'sudo opensnoop -p'
alias fhere   'mfind -onlyin .'
alias fname   'mfind -name'
alias stylus  'stylus -u nib'
alias ports   'lsof -i | g listen'
alias nosleep 'pmset noidle'
alias gs      'git status'
alias ga      'git add'
alias gc      'git commit -m'
alias gp      'git pull origin'
alias gps     'git push origin'
alias gd      'git diff'
alias gco     'git checkout'
alias gb      'git checkout -b'
alias gl      'git log --color --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%C(bold blue)<%an>%Creset" --abbrev-commit'
alias bru     'brew update; and brew outdated'
alias brug    'brew upgrade; and brew cleanup'
alias pgrep   'pgrep -i'
alias pkill   'pkill -i'
